config/routes.rb
Rails.application.routes.draw do
  get 'answers/index'

  get 'welcome/index'

  get 'questions/index'

  resources :questions
  root 'questions#index'

  resources :answers

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :title, :content, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  validates :title, :content, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def new
    @answer = Answer.new
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to @answer.question
    else
      render 'new'
    end

  end

  def update
    @answer = Answer.find(params[:id])

    if @answer.update(article_params)
      redirect_to @answer
    else
      render 'edit'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    redirect_to answers_path
  end

  private
  def answer_params
    params.require(:answer).permit(:title, :content, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new(question: @question)
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end

  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_answer.html.erb
<li>
  <h3><%= answer.title %></h3>
  <p><%= answer.content %></p>
</li>

app/views/answers/_form.html.erb
<%= form_for @answer do |f| %>
  <%= f.hidden_field :question_id, :value => @question.id%>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/_new.html.erb
<%= form_for :question, url: questions_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<li>
  <h2><%= link_to question.title, question_path(question) %> - <%= link_to 'Edit', edit_question_path(question) %> - <%= link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are you sure?' } %></h2>
  <p><%= question.content %></p>
  <ul>
    <%= render question.answers %>
  </ul>
</li>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>All Questions:</h1>

<ol>
  <%= render @questions %>
</ol>

<h2>New Question:</h2>
<%= render "questions/form" %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<%= render partial: "question", object: @question %>

<%= link_to 'Back', questions_path %>

<h2>New Answer:</h2>
<%= render partial: "answers/form" %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'All Questions', controller: 'questions' %>